# Generated by Django 5.0.4 on 2024-04-27 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='end_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done_at',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
