# Generated by Django 5.0.4 on 2024-04-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('to_do', '0002_remove_todo_end_date_todo_created_at_todo_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
            preserve_default=False,
        ),
    ]
