# Generated by Django 5.0.4 on 2024-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_remove_todo_category_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_at',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
